platform :osx, '10.11'
use_frameworks!

target 'Instagram' do
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireImage', '~> 3.3'
    pod 'PromiseKit', '~> 4.3'

    target 'InstagramTests' do
        inherit! :search_paths
        pod 'Mockingjay', '~> 2.0'
    end
end
